'use server';
/**
 * @fileOverview This file contains a Genkit flow that provides an explanation of the correct answer to a quiz question,
 * leveraging an LLM to generate a concise and informative summary of the key concepts related to the question.
 *  It now also incorporates a tool to identify keywords for search.
 * - answerExplanationWithLLM - A function that handles the answer explanation process.
 * - AnswerExplanationWithLLMInput - The input type for the answerExplanationWithLLM function.
 * - AnswerExplanationWithLLMOutput - The return type for the answerExplanationWithLLM function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerExplanationWithLLMInputSchema = z.object({
  question: z.string().describe('The quiz question.'),
  correctAnswer: z.string().describe('The correct answer to the question.'),
  userAnswer: z.string().describe('The answer provided by the user.'),
  explanation: z.string().describe('The original explanation of the correct answer.'),
});
export type AnswerExplanationWithLLMInput = z.infer<typeof AnswerExplanationWithLLMInputSchema>;

const AnswerExplanationWithLLMOutputSchema = z.object({
  llmExplanation: z.string().describe('A concise and informative summary of the key concepts related to the question, generated by an LLM.'),
  keywords: z.array(z.string()).describe('Keywords related to the question and answer that can be used for search.'),
});
export type AnswerExplanationWithLLMOutput = z.infer<typeof AnswerExplanationWithLLMOutputSchema>;

export async function answerExplanationWithLLM(input: AnswerExplanationWithLLMInput): Promise<AnswerExplanationWithLLMOutput> {
  return answerExplanationWithLLMFlow(input);
}

const identifyKeywords = ai.defineTool({
  name: 'identifyKeywords',
  description: 'Identifies keywords in a given text.',
  inputSchema: z.object({
    text: z.string().describe('The text to analyze for keywords.'),
  }),
  outputSchema: z.array(z.string()).describe('An array of keywords identified in the text.'),
}, async (input) => {
  // Basic keyword identification (replace with a more sophisticated method if needed)
  return input.text.split(/\s+/).filter(word => word.length > 3);
});

const answerExplanationPrompt = ai.definePrompt({
  name: 'answerExplanationPrompt',
  input: {schema: AnswerExplanationWithLLMInputSchema},
  output: {schema: z.object({ llmExplanation: z.string() })},
  tools: [identifyKeywords],
  prompt: `You are an expert in explaining complex topics in a simple and easy-to-understand way.

  The user has just answered a quiz question. The question, the correct answer, the user\'s answer and the original explanation are given below.

  Your task is to provide a concise and informative summary of the key concepts related to the question, so the user can better understand the material and improve their learning.

  Question: {{{question}}}
  Correct Answer: {{{correctAnswer}}}
  User Answer: {{{userAnswer}}}
  Original Explanation: {{{explanation}}}

  Concise LLM Explanation:`, // Prompt is now complete.
});

const answerExplanationWithLLMFlow = ai.defineFlow(
  {
    name: 'answerExplanationWithLLMFlow',
    inputSchema: AnswerExplanationWithLLMInputSchema,
    outputSchema: AnswerExplanationWithLLMOutputSchema,
  },
  async input => {
    const { output } = await answerExplanationPrompt(input);
    const keywords = await identifyKeywords({ text: `${input.question} ${input.correctAnswer} ${input.explanation}` });
    return { llmExplanation: output!.llmExplanation, keywords };
  }
);

